### ISSUE TITLE
Components in obspy stream are labeled wrong

### ISSUE THREAD

**Issue by mchlrnwld** [krischer/instaseis#10]
When using get_seismograms() to store wavefields as an obspy stream, the component labeling is wrong.

Here is the (correct) result when using the GUI:
![instaseis_gui](https://cloud.githubusercontent.com/assets/8170486/8088412/7176b9d0-0fa1-11e5-9947-14484d40549f.png)

Here is the result when using the code provided below:
![obspy_stream](https://cloud.githubusercontent.com/assets/8170486/8088413/717c16c8-0fa1-11e5-9cdc-e24462403ac4.png)

If this is compared with the output from the GUI, it is clear that simply N and E are switched/labeled wrong in the obspy stream.
This is the code that has been used to store the obspy stream:

```python
import instaseis

db = instaseis.open_db("/import/neptun-seismology/instaseis/ak135f/")
rec = instaseis.Receiver(latitude=-0.2,longitude=34.5)
src = instaseis.Source(latitude=0.0,longitude=35.0, depth_in_m=2000, m_rr=0, m_tt=0, m_pp=0, m_rt=0, m_rp=0, m_tp=1.0e17)

sm = db.get_seismograms(source=src,receiver=rec, kind='displacement', components=('Z','N','E'))

sm.plot()
```

**Comment by kasra-hosseini** [comment]
@martinvandriel Can it be due to the *label_map* (line 352) in *instaseis_gui.py*? Here is the code:

```
label_map = {0: {"z": "vertical", "n": "east", "e": "north"},
             1: {"z": "vertical", "n": "radial", "e": "transverse"}}
```

Here "n" is mapped to "east" and "e" is mapped to "north". Not sure about the reason and whether this is the case for non-gui get_seismogram.

**Comment by martinvandriel** [comment]
Interesting. I would say it's wrong in the GUI though:
![instaseis_gui](https://cloud.githubusercontent.com/assets/2306288/8102627/c118d588-1021-11e5-886d-6ed7f121d032.png)
So probably you are right, Kasra.

**Comment by mchlrnwld** [comment]
You're right. The GUI is wrong, the traces in the obspy streams are labeled correctly.
