### ISSUE TITLE
slip / sliprate in /info

### ISSUE THREAD

**Issue by martinvandriel** [krischer/instaseis#16]
to reduce size of /info we could either make slip and sliprate optional or strip them from all the trailing zeros

**Comment by krischer** [comment]
Already solved in 1e1b6558eac43ed5a22d18f2c37edb4f6d8f037a ;-)

Don't request gzipped data:
```bash
krischer@ten:~$ curl -s -D - http://ten:9101/info -o /dev/null | grep "Content-Length"
Content-Length: 77319
```

Request gzipped data:
```bash
krischer@ten:~$ curl -s -D - -H "Accept-Encoding: gzip" http://ten:9101/info -o /dev/null | grep "Content-Length"
Content-Length: 1144
```

No need to special case anything and it should be small enough. The zeros compress to almost nothing.

I'm writing an email right now.
