### ISSUE TITLE
Use appropriate MIME type for miniSEED with Content-Type header in HTTP responses

### ISSUE THREAD

**Issue by CTrabant** [krischer/instaseis#17]
Instaseis is currently documented to use `application/octet-stream` for miniSEED
http://www.instaseis.net/routes/seismograms.html
http://instaseis.net/routes/greens_function.html

Suggestion is to use the more specific MIME type of `application/vnd.fdsn.mseed`

**Comment by krischer** [comment]
Ah nice. I was not aware that exists. Will do.
