### ISSUE TITLE
Custom source time function in `/seismograms` route

### ISSUE THREAD

**Issue by krischer** [krischer/instaseis#21]
We would like to have the possibility to specify a custom source time function in the `/seismograms` route. I propose to use a JSON file akin to the following:

```json
{
    "units": "moment_rate",
    "relative_origin_time_in_sec": 15.23,
    "sample_spacing": 0.1,
    "number_of_samples": 1500,
    "data": [0.2, 4, 25, 5, 2, 5, ...]
}
```
Would this work for all intended purposes?

The `relative_origin_time_in_sec` argument defines what should be considered the origin time of the event for all further stages in seconds relative to the first sample in the source time function. Thus one can set the origin time to the peak of something or the central moment or whatever else.

Please comment.

**Comment by sstaehler** [comment]
Good idea. Two questions:
 - Units: Is this field supposed to have a meaning? In the sense of allowing to specify the STF in terms of moment rate (the usual way) or moment?
 - Normalization: Will you enfore normalization of the STF to 1?

**Comment by krischer** [comment]
> Units: Is this field supposed to have a meaning? In the sense of allowing to specify the STF in terms of moment rate (the usual way) or moment?

Yea. Is there any use for this? Just fixing it is of course simpler.

> Normalization: Will you enfore normalization of the STF to 1?

I was planning on doing that. Any reason not to?

Another thing: I don't want to deal with downsampling so we'll only accept STFs that are lower sampled than the database. Should the largest possible sampling rate rather be half the dominant period (dominant period is then then nyquist)?

**Comment by sstaehler** [comment]
> Yea. Is there any use for this? Just fixing it is of course simpler.

I don't think, I've ever seen somebody working with data who defined the STF in terms of moment.
Alas, SpecFEM and AxiSEM and probably other numerical codes do, so it might be useful to allow to define it in terms of moment.

> I was planning on doing that. Any reason not to?

You mean you normalize it or you enforce it to be? Either way should be fine. Maybe enforce it to be normalized (but be sure to give a meaningful error message ;) )

> Another thing: I don't want to deal with downsampling so we'll only accept STFs that are lower sampled than the database. Should the largest possible sampling rate rather be half the dominant period (dominant period is then then nyquist)?

I did not see the alternatives you were offering. Why not sampling rate (i.e. quarter of the dominant period)?

**Comment by krischer** [comment]
From @tnissen 

> AS for the custom STF... I agree having the option of moment and moment rate is useful and flexible (side note to Simon: people use at least SPECFEM to work with data:)) - anyone providing their own STF should be aware of what the time series represent. data: Is the first sample at the first \delta t? If so, it assumes that the STF starts at zero, right? This is not the case for a lot of Karin's inverted STF, which do start at non-zero values (it is obviously non-physical but driven by the inversion). As such I'd suggest to have the data series allow for this case.
> 
> I would think the best and easiest way to see if it fits all purposes is to discuss this with folks that generate/use their own STF: For instance Kasra/Karin, Fichtner gang, Tromp gang... SImon will surely know more STF inversion folks? Strasbourg i think?

**Comment by kasra-hosseini** [comment]
In short, what we need is to convolve the instaseis synthetics with inverted STFs, e.g:

![stfs_grp_0054 2009 267 a](https://cloud.githubusercontent.com/assets/1899856/10995855/379d8faa-8480-11e5-8a5b-7b6ba9e014e8.png)

In our new processing scheme based on instaseis, I am doing this externally with the following steps:
```
1. generate a synthetic smgr with instaseis and inverted source info.
2. re-sample the synthetic to 10Hz, i.e. up-sampling for instaseis.
3. syn_waveform = np.convolve(syn_waveform, stf)
And of course taking into account the starting time of the stf.
```
The problem with the above method is that we have two STFs: one from instaseis and the other our inverted STF. I have not done that yet, but first I should deconvolve the instaseis STF and then convolve our STF...something similar to the built-in function of instaseis for slip-rate. That is basically all we need to generate the final synthetic waveforms.

**Comment by krischer** [comment]
Thanks for this.

That use case would supported by the JSON file (deconvolve instaseis STF + convolve with new one) with two exceptions:

1. We will not accept source time functions that have a sampling rate which is higher then mesh_period / 2.0 (nyquist of the mesh period). So for a 2 second database the highest allowed sampling rate of the source time function would be 1 Hz. This safeguards against introducing frequencies that are not propagated in the database and we don't have to deal with downsampling/alias filtering the STF.
2. It must start and end with zeros to not run into issues with the FFT.

**Comment by kasra-hosseini** [comment]
Thanks for your reply. Don't you think it would be better if we have a functionality to re-sample the STF in instaseis? Like a functionality to check the sampling rate of the STF and if it is not compatible, change it internally and giving a warning message or so. Though I totally understand the problem with downsampling and alias filtering.  Honestly, I am not sure. Maybe it is actually the responsibility of the user to take care of it.

**Comment by krischer** [comment]
I feel pretty strongly that this is the responsibility of the users - there is just no way it can be done automatically without confusing users. Instaseis would of course upsample once I implement this issue's suggestion.

**Comment by alexhutko** [comment]
We support adding this feature.  From our perspective, the suggested parameters are fine as are the requirements for start/end with zero and the sample rate.  We can easily document this and return appropriate error messages.

**Comment by alexhutko** [comment]
This issue is continued here:  https://github.com/krischer/instaseis/pull/37
