### ISSUE TITLE
Store specified scale value in SAC header USER0 field

### ISSUE THREAD

**Issue by CTrabant** [krischer/instaseis#26]
To document the applied `scale` factor, consider storing in generated SAC headers in the `SCALE` header.  This header value is documented as "unused" making it safe to use for storing the value:
http://ds.iris.edu/files/sac-manual/manual/file_format.html

**Comment by krischer** [comment]
I'll implement this tomorrow if you want to have it.

I would rather use one of the other unused header fields. The reasoning is that some other software programs might interpret the `SCALE` factor as a factor they still have to apply to the data before it is valid. That's how I would interpret it at least. Even though the SAC format spec states that it is not used there is very likely some piece of software out there that does use it - I cannot find it right now but I am very sure we had this discussion once in ObsPy and we chose to ignore the scale parameter in sac files as it led to some issues.

That being said I trust your experience and judgement in this so just let me know.

**Comment by CTrabant** [comment]
Hmm, after yet another re-review of the implications of setting SCALE I am in agreement that it's probably better to be avoided.  In addition to changing and improper use in older versions of sac, there is no way to know if the value has been applied or not.

How about `user0` field then?

**Comment by krischer** [comment]
Done in 01d0564d75566bd106ff97abd51764042cd7d6aa and 37f0bae14dd275c90cbf7728cb6d0b820b6f0448.

All the custom header values currently set:

* ``KUSER0``: "InstSeis"
* ``KUSER1``: The first eight letters of the Instaseis version used to generate the waveforms.
* ``KUSER2``: The first eight letters of the velocity model name.
* ``USER0``: The scale factor used to generate the waveforms.

They are now also documented here:
