### ISSUE TITLE
greens_function?

### ISSUE THREAD

**Issue by alexhutko** [krischer/instaseis#28]
Hi,

If a user wants to use their own source for instaseis synthetics, rather than deconvolving the default source of the data base, can they just use greens_function?  I didn't really understand the explanation given on the instaseis page.  Also, an example for usage would be nice.

http://instaseis.net/routes/greens_function.html

Thaks,
Alex

**Comment by krischer** [comment]
Hi,

no that cannot be used for your intended purpose. The `/greens_function` route is used for moment tensor inversions. One gets back all the independent components and by summing in a certain way one can construct the seismogram for any moment tensor without having to redownload something. Check the referred paper for the exact formulas.

This might be worthwhile to include into syngine but it does require some postprocessing before it generates a usable seismograms (that will then still have AxiSEMs original source time function convolved with it).

**Comment by tnissen** [comment]
Maybe it would be clearer to call this /green_tensor rather than 
greens_function in instaseis? From my experience, people often call any 
deconvolved trace a Green's function...

So is there no way for users of syngine to provide, say, a CMTSOLUTION 
and get a Green function (q.e.d.) without having to deconvolving the 
default source? I seem to have lost track of this discussion earlier...





On 11/23/15 20:14, Lion Krischer wrote:
>
> Hi,
>
> no that cannot be used for your intended purpose. The 
> |/greens_function| route is used for moment tensor inversions. One 
> gets back all the independent components and by summing in a certain 
> way one can construct the seismogram for any moment tensor without 
> having to redownload something. Check the referred paper for the exact 
> formulas.
>
> This might be worthwhile to include into syngine but it does require 
> some postprocessing before it generates a usable seismograms (that 
> will then still have AxiSEMs original source time function convolved 
> with it).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/krischer/instaseis/issues/28#issuecomment-159050945>.
>

-- 
Tarje

<>--<>--<>--<>--<>--<>
Dept. of Earth Sciences
Oxford University
South Parks Road
Oxford OX1 3AN; UK
tel: +44 1865 282149
web: seis.earth.ox.ac.uk
<>--<>--<>--<>--<>--<>

**Comment by krischer** [comment]
> Maybe it would be clearer to call this /green_tensor rather than greens_function in instaseis? From my experience, people often call any deconvolved trace a Green's function...

I don't mind renaming the route but I know seiscomp already uses it for their MT inversion things so that makes it a bit more complicated. @martinvandriel I leave that decision to you.

> So is there no way for users of syngine to provide, say, a CMTSOLUTION and get a Green function (q.e.d.) without having to deconvolving the default source? I seem to have lost track of this discussion earlier...

I'm not entirely sure what you mean. Just deconvolving the default source is not a stable operation.

**Comment by martinvandriel** [comment]
@tnissen Actually, the function returns Green's functions for 4 elemental sources in your sense and no tensor. This is what the paper says:

> Adeviatoric point source can be represented by using Green’s functions for three fundamental faults [...] However, for a complete moment tensor, M, we must also include the explosion Green’s functions [...] SS is the vertical strike-slip Green’s function, DS is the vertical dip-slip Green’s function, DD is the 45◦ dip-slip Green’s function and EP is the explosion Green’s function.

So I could see reasons to rename it to /greens_functions with s at the end, but I woud want to avoid the hassle of propagating that change to seiscomp3.

**Comment by krischer** [comment]
Closing this for now as I don't think there is anything to do. The `/greens_function` name might be a bit ambiguous but the documentation is IMHO good enough to clarify that.
