### ISSUE TITLE
please add O to SAC header

### ISSUE THREAD

**Issue by alexhutko** [krischer/instaseis#32]
Please add O to the SAC header.  Right now the kztime is just the start time of the trace and the event origin time is not present.  One would have to remember the request.

O is an offset in seconds relative to the begin time.

https://ds.iris.edu/files/sac-manual/manual/file_format.html

**Comment by krischer** [comment]
That should already be set by instaseis. I just tested it with the raw instaseis server. Do you maybe strip it in your middleware?

While you are at it: Can you check if it is set to the correct value?

**Comment by alexhutko** [comment]
Sorry for the confusion.  It gets routed to OMARKER which is apparently the new version of O.  Can't find the documentation, but I think we're OK with this one.  Thanks Lion.

https://ds.iris.edu/ds/nodes/dmc/kb/questions/133/cannot-find-origin-time-in-sac-header/
