### ISSUE TITLE
CMTSOLUTION file reader

### ISSUE THREAD

**Issue by martinvandriel** [krischer/instaseis#33]
Reported by Luis Rivera:

The fifth character in the first line of the cmtsolution file (from globalcmt) is blank for "old" events, but it is not so for recent events. However it seems to me that instaseis requires it to be blank.

**Comment by krischer** [comment]
865869ee7d5c0174705ae2f036daf1b3cf25717f pushes the CMTSOLUTION parsing to ObsPy which gained that functionality a while ago. The mentioned issue is also true in ObsPy, but dealt with in this PR: https://github.com/obspy/obspy/pull/1479

A new ObsPy version should be released soon with that fix.
