### ISSUE TITLE
Releasing 1.0

### ISSUE THREAD

**Issue by krischer** [krischer/instaseis#43]
Hi all,

I went ahead and fixed all outstanding features and bugs in Instaseis. I'm not aware of anything else that really needs to be done. I propose to wait one or two weeks to see if Syngine requires anything else and then we release Instaseis version 1.0. 

Sounds good?

Cheers!

Lion

**Comment by alexhutko** [comment]
Yup.

I’m testing now.

We’ll keep you updated.  Yay version 0.999!!

Alex

**Comment by sstaehler** [comment]
@krischer Great! 

Just one more nagging: The discussion on the sampling rate of STFs stopped abruptly, some time ago. 
In the meantime, there was a discussion between several QuakeML stakeholders and STFs will most likely be a part of the "Basic Event Description" package of QuakeML 1.2. Usually they will have higher sampling rates than the typical Instaseis databas. Therefore, I think it will be necessary that Instaseis can handle the case that STFs have a higher sampling rate than the database.

**Comment by alexhutko** [comment]
Hi Lion,

Can you please tag your latest version as v1.0.  If we catch any issues in higher order features (STF/FFM), those can just go into updates, but so far everything else looks like it's working.

Thanks,
Alex

**Comment by krischer** [comment]
Done. Installation can now also be performed with

```bash
$ pip install instaseis
```

I'm also trying to get conda packages done as soon as possible.

**Comment by krischer** [comment]
It can now also be installed with

```bash
$ conda install -c conda-forge
```

which will also install all of its dependencies so that makes it really easy to get instaseis now :-)
