### ISSUE TITLE
LPSPOL and LCALDA values in the SAC header

### ISSUE THREAD

**Issue by manoch-iris** [krischer/instaseis#45]
Comparing 2 SAC headers, one produced using the production instaseis version at DMC and the other generated by the newly release version of the instaseis, indicates that the values of the following fields have switched!

SAC produced by the previous version of instaseis:
      LPSPOL = TRUE
      LCALDA = FALSE

SAC produced by the new version of instaseis:
      LPSPOL = FALSE
      LCALDA = TRUE

Is this change intentional?

Thanks

**Comment by CTrabant** [comment]
Note, the production system is using ObsPy 0.10.2 and the test/beta system is using ObsPy 1.0.2.

**Comment by krischer** [comment]
Yes this is caused by the updated ObsPy version - I opened an issue here: https://github.com/obspy/obspy/issues/1507

I'll change this for instaseis as I believe the default values should be:

LPSPOL = TRUE
LCALDA = FALSE

Let me know if you disagree.
