### ISSUE TITLE
Finite source 'NotImplementedError'

### ISSUE THREAD

**Issue by Thomas-Ulrich** [krischer/instaseis#62]
Hi,

I have a finite source model (Kaikoura earthquake) and I would like to test its ability to replicate the teleseismic data.  Instaseis is running well with a single point source, but when trying to deal with several point sources, I m getting the following error:

> (obspy) ulrich@tegern:/export/data/ulrich/SumatraEQ$ python testInstaseis.py 
Traceback (most recent call last):
  File "testInstaseis.py", line 29, in <module>
    st = db.get_seismograms(source=sources, receiver=rec)
  File "/home/ulrich/MyLibs/anaconda2/envs/obspy/lib/python2.7/site-packages/instaseis/database_interfaces/base_instaseis_db.py", line 244, in get_seismograms
    kind=kind, dt=dt)
  File "/home/ulrich/MyLibs/anaconda2/envs/obspy/lib/python2.7/site-packages/instaseis/database_interfaces/base_instaseis_db.py", line 602, in _get_seismograms_sanity_checks
    source = Source.parse(source)
  File "/home/ulrich/MyLibs/anaconda2/envs/obspy/lib/python2.7/site-packages/instaseis/source.py", line 400, in parse
    raise NotImplementedError
NotImplementedError

Is there a work-around? Here is my (very basic code). I ve precompile source time functions and moment tensors in a hdf5 file:

>import instaseis
import obspy
import h5py
from obspy.clients.fdsn import Client
from obspy import UTCDateTime
db = instaseis.open_db('/export/data/ulrich/Instaseis/10s_PREM_ANI_FORCES')
c = Client("IRIS")
rec = c.get_stations(network="IU", station="FUNA", level="station", starttime=UTCDateTime(2016, 11, 13, 11, 02, 56.34))
h5f = h5py.File('PointSourceKaikoura.h5')
NormalizedMomentRate = h5f['NormalizedMomentRate'][:,:]
nsource, ndt = NormalizedMomentRate.shape
xyz = h5f['xyz'][:,:]
MomentTensor = h5f['MomentTensor'][:,:]
dt=1
h5f.close()
lps= []
for isrc in range(nsource):
   source = instaseis.Source( latitude=xyz[isrc,1], longitude=xyz[isrc,0], depth_in_m=-xyz[isrc,2],
      m_rr = MomentTensor[isrc,0], m_tt =MomentTensor[isrc,1], m_pp =MomentTensor[isrc,2],m_rt =MomentTensor[isrc,3],m_rp =MomentTensor[isrc,4],m_tp =MomentTensor[isrc,5],origin_time=UTCDateTime(2016, 11, 13, 11, 02, 56.34), sliprate = NormalizedMomentRate[isrc,:], dt=1)
   lps.append(source)
sources = instaseis.source.FiniteSource(pointsources=lps)
st = db.get_seismograms(source=sources, receiver=rec)
st.plot(size=(800, 600))

Thanks in advance,

Thomas.

**Comment by krischer** [comment]
You have to use the `.get_seismograms_finite_source()` method for this: http://instaseis.net/instaseis.html#instaseis.database_interfaces.base_instaseis_db.BaseInstaseisDB.get_seismograms_finite_source

Cheers!

Lion

**Comment by Thomas-Ulrich** [comment]
ok, it works, thx!

**Comment by krischer** [comment]
It will now raise a helpful error message with #63.
