### ISSUE TITLE
Trouble identifying arrival

### ISSUE THREAD

**Issue by Nimmitha87** [krischer/instaseis#72]
Hi all, 
I am interested in identifying phases at teleseismic distances, but at the moment I am having trouble understanding a particular phase that appears between PKIKP and PKP. The following is for an explosion source at a depth of 300km. The plot is for a station at 165gcd. I've used the ak135_f1s data base. 
```import instaseis
import numpy as np
import matplotlib.pyplot as plt

#read instaseis streams
db = instaseis.open_db("syngine://ak135f_1s")
src = instaseis.Source(latitude=90, longitude=0, depth_in_m=300000.0,
    m_rr=10e7, m_tt=10e7, m_pp=10e7)

i=75 #station latitude
PKIKP_arr=1168.12 #red
PKP_arr=1226.6 #green
q_arr=1187 #black
rec = instaseis.Receiver(latitude=-i, longitude=0)

st = db.get_seismograms(source=src,receiver=rec)

t = st.select(channel='MXZ')[0]

time = np.linspace(0,t.stats.npts*t.stats.delta,t.stats.npts)

#for velocity
der = np.diff(t.data) / np.diff(time)
new_time = (time[:-1] + time[1:]) / 2

xlim = [1140,1250]

#displacemt plot
fig_1=plt.figure()
ax=fig_1.add_axes([0,1,1,1])
ax.plot(time,t.data)
ax.set_xlim(xlim)
ax.set_xlabel('time')
ax.set_ylabel('displacement')
ax.axvline(PKIKP_arr,color='r',linestyle='dashed')
ax.axvline(PKP_arr,color='g',linestyle='dashed')
ax.axvline(q_arr,color='k',linestyle='dashed')

#displacemt plot
fig_2=plt.figure()
ax_2=fig_2.add_axes([0,1,1,1])
ax_2.plot(new_time,der)
ax_2.set_xlim(xlim)
ax_2.set_xlabel('time')
ax_2.set_ylabel('velocity')
ax_2.axvline(PKIKP_arr,color='r',linestyle='dashed')
ax_2.axvline(PKP_arr,color='g',linestyle='dashed')
ax_2.axvline(q_arr,color='k',linestyle='dashed')
```

The doubtful arrival is close to 1187s
![image](https://user-images.githubusercontent.com/62071971/76446238-216c9180-639d-11ea-88be-c8615b5503d3.png)

I am new to using Instaseis and any help in this regard is highly appreciated.

**Comment by martinvandriel** [comment]
Hi, 

I would try to move the source closer and further away, up and down to get an idea of the moveout. Then you can use taup to check various phases for arrival time and moveout to identify it uniquely.

Cheers,
Martin

**Comment by krischer** [comment]
It is also a fairly isolated phase so I imaging TauP would give you a decent answer. Make sure to use the same model in TauP as for instaseis.

I'm closing this as there is nothing for us to do here in terms of code development.
