### ISSUE TITLE
epicentral_distance_in_degree  and get_seismograms

### ISSUE THREAD

**Issue by manoch-iris** [krischer/instaseis#81]
Hello,

Is there any technical reasons why **epicentral_distance_in_degree** is not supported by **get_seismograms** and only works with **get_greens_function**?

Thanks,

--manoch

**Comment by martinvandriel** [comment]
Hi,

I guess it's not a technical reason, more semantics of what the horizontal components (North, East) are in case you don't have the absolute locations. Of course for radial and transverse this would indeed be a reasonable input. For the greens functions this just follows the definitions of the particular source decomposition in the Minson & Dreger paper.

Cheers,
Martin

**Comment by manoch-iris** [comment]
Hi Martin,

Thank you so much for your quick reply. This make sense and thanks for clarifying.

Cheers,
--manoch
