### ISSUE TITLE
Include checks whether specified src-rec parameters are within loaded database

### ISSUE THREAD

**Issue by pjkoelemeijer** [krischer/instaseis#9]
When the specified source depth is outside the loaded database domain, the error is not very insightful: e.g.  ValueError: Element not found

Consistency checks for source depth, and source-receiver distance may be useful, particularly when a local database (e.g. of restricted epicentral distance) is used.

**Comment by krischer** [comment]
Better late then never. The last couple of commit to the master fix this.
